DROP TABLE IF EXISTS attack;
DROP TABLE IF EXISTS char;
CREATE TABLE char
(
 id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 class_name text NOT NULL,
 has_spells boolean NOT NULL,
 hitpoints integer NOT NULL
);







