-- psql -U postgres -d adventurandom -f ./seeds/seed.adventurandom.sql

BEGIN;

INSERT INTO char
    (class_name, has_spells, hitpoints)
VALUES
    ('Barbarian' , false, 20),
    ('Bard', true, 15),
    ('Cleric', true, 10),
    ('Druid', true, 15),
    ('Fighter' , false, 58),
    ('Monk', false, 19),
    ('Paladin', true, 20),
    ('Ranger', false, 10),
    ('Rogue', false, 10),
    ('Sorcerer' , true, 20),
    ('Warlock', true, 20),
    ('Wizard', true, 10);

 
INSERT INTO attack
    (damage_type, damage_die, is_spell, attack_name)
VALUES
    ('slashing', 12, false, 'Greataxe'),
    ('bludgeoning', 8, false, 'Warhammer'),
    ('bludgeoning', 12, false, 'Quarterstaff'),
    ('piercing', 8, false, 'Crossbow'),
    ('piercing', 12, false, 'Throwing stars'),
    ('piercing', 8, false, 'Longbow'),
    ('bludgeoning', 12, false, 'Sling'),
    ('bludgeoning', 8, false, 'Mace'),
    ('bludgeoning', 12, false, 'Flail'),
    ('bludgeoning', 8, false, 'Morningstar'),
    ('force', 12, true, 'Magic Missile'),
    ('lightning', 8, true, 'Shocking Grasp'),
    ('cold', 12, true, 'Freezing Sphere'),
    ('acid', 6, true, 'Acid Splash'),
    ('cold', 12, true, 'Chill Touch'),
    ('radiant', 8, true, 'Banishing Smite'),
    ('necrotic', 12, true, 'Bestow Curse'),
    ('poison', 8, true, 'Black Tentacles'),
    ('force', 12, true, 'Catapult'),
    ('necrotic', 8, true, 'Blight'),
    ('radiant', 12, true, 'Blinding Smite'),
    ('fire', 8, true, 'Burning Hands'),
    ('psychic', 12, true, 'Chaos Bolt'),
    ('acid', 8, true, 'Chromatic Orb'),
    ('poison', 12, true, 'Cloudkill'),
    ('bludgeoning', 8, true, 'Flurry of Blows'),
    ('bludgeoning', 12, true, 'Stunning Strike'),
    ('bludgeoning', 8, true, 'Fists of the Wind'),
    ('bludgeoning', 12, true, 'Shoulder Tackle'),
    ('fire', 8, true, 'Fists of Fire'),
    ('bludgeoning', 12, true, 'Rockbreaker'),
    ('bludgeoning', 8, true, 'Howling Fist'),
    ('bludgeoning', 12, true, 'Dragon Kick'),
    ('bludgeoning', 8, true, 'Four-point Fury'),
    ('bludgeoning', 12, true, 'Fists of the Earth'),
    ('bludgeoning', 8, true, 'The Forbidden Chakra'),
    ('bludgeoning', 12, true, 'Vicious Mockery'),
    ('bludgeoning', 8, true, 'Riddle of Fire'),
    ('fire', 10, true, 'Fire Bolt'),
    ('slashing', 10, true, 'Dagger'),
    ('slashing', 100, true, 'Sneak Attack');

INSERT INTO char_attack
    (char_id, att_id)
VALUES
    (1,1),
    (3,1),
    (5,1),
    (7,1),
    (1,2),
    (5,2),
    (7,2),
    (1,3),
    (2,3),
    (3,3),
    (4,3),
    (5,3),
    (6,3),
    (7,3),
    (8,3),
    (1,4),
    (2,4),
    (4,4),
    (5,4),
    (7,4),
    (8,4),
    (9,4),
    (1,5),
    (4,5),
    (5,5),
    (7,5),
    (8,5),
    (9,5),
    (1,6),
    (2,6),
    (4,6),
    (5,6),
    (7,6),
    (8,6),
    (1,7),
    (2,7),
    (4,7),
    (5,7),
    (7,7),
    (8,7),
    (9,7),
    (1,8),
    (3,8),
    (5,8),
    (7,8),
    (1,9),
    (3,9),
    (5,9),
    (7,9),
    (1,10),
    (3,10),
    (5,10),
    (7,10),
    (3,12),
    (4,12),
    (10,12),
    (11,12),
    (12,12),
    (4,13),
    (10,13),
    (11,13),
    (12,13),
    (4,14),
    (10,14),
    (11,14),
    (12,14),
    (4,15),
    (10,15),
    (11,15),
    (12,15),
    (3,16),
    (7,16),
    (10,16),
    (11,16),
    (12,16),
    (2,17),
    (3,17),
    (10,17),
    (11,17),
    (12,17),
    (10,18),
    (11,18),
    (12,18),
    (10,19),
    (11,19),
    (12,19),
    (3,20),
    (4,20),
    (7,20),
    (10,20),
    (11,20),
    (12,20),
    (3,21),
    (10,21),
    (11,21),
    (12,21),
    (3,22),
    (4,22),
    (10,22),
    (11,22),
    (12,22),
    (10,23),
    (11,23),
    (12,23),
    (10,24),
    (11,24),
    (12,24),
    (10,25),
    (11,25),
    (12,25),
    (6,26),
    (6,27),
    (6,28),
    (6,29),
    (6,30),
    (6,31),
    (6,32),
    (6,33),
    (6,34),
    (6,35),
    (6,36),
    (2,37),
    (6,37),
    (2,38),
    (6,38),
    (3,39),
    (4,39),
    (10,39),
    (11,39),
    (12,39),
    (9,39),
    (9,39);

INSERT INTO monster
    (monster_name, hitpoints, damage_die)
VALUES
    ('Goblin', 12, 6),
    ('Chain Devil', 35, 12),
    ('Bugbear', 30, 12),
    ('Bandit', 20, 10),
    ('Vampire', 50, 20),
    ('Vampire thrall', 30, 12),
    ('Flumph', 15, 8),
    ('Skeleton archer', 10, 8),
    ('Boar', 10, 6),
    ('Xorn', 26, 12),
    ('Wyvern', 55, 20),
    ('Griffon', 50, 20),
    ('Efreeti', 50, 20),
    ('Troll', 40, 12),
    ('Elf scout', 15, 6),
    ('Dwarf warrior', 25, 8),
    ('Drow assassin', 25, 10),
    ('Manticore', 50, 12),
    ('Gelatinous cube', 99, 20),
    ('Bear', 40, 12);

INSERT INTO location_flavor
    (location_flavor_string)
VALUES
    ('of the Twisted Root'),
    ('of the Mad King'),
    ('from Hell'),
    ('of Broken Promises'),
    ('of Dreams'),
    ('of Mist'),
    ('of Moonlight'),
    ('of Ages'),
    ('of Eternity'),
    ('of Magic'),
    ('of Mana'),
    ('of Secrets'),
    ('of Lost Souls'),
    ('of Insanity'),
    ('of Hatred'),
    ('of Chaos'),
    ('of Catastrophe'),
    ('of Cats'),
    ('of Darkness'),
    ('of Death'),
    ('of Devils'),
    ('of Disease'),
    ('of Uncomfort'),
    ('of Ruin'),
    ('of Screams'),
    ('of Power'),
    ('of Criminals'),
    ('of Winter'),
    ('of Woe'),
    ('of Worms'),
    ('of Worry'),
    ('of Spite'),
    ('of the Fathers'),
    ('of the Grandfathers'),
    ('of the Sons'),
    ('of the Three Brothers'),
    ('of the Three Sisters'),
    ('of Seven Paths'),
    ('of Valor'),
    ('of Crime'),
    ('of Sorrow'),
    ('of War'),
    ('of No Escape'),
    ('Full of Bones'),
    ('near Zadash'),
    ('near Rohan'),
    ('near Winterdeep'),
    ('near Whiterun'),
    ('near Dawnstar'),
    ('near Falkreath'),
    ('near Bajor'),
    ('near Tellar Prime'),
    ('of Cracked Pearls'),
    ('that is not a Castle'),
    ('that is not a Graveyard'),
    ('that is not a Dungeon'),
    ('that is not a Forest');

COMMIT;