-- *************** SqlDBM: PostgreSQL ****************;
-- ***************************************************;


-- ************************************** "attacks"
DROP TABLE IF EXISTS attacks;
CREATE TABLE attacks
(
 id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 damage_type text NOT NULL,
 damage_die  integer NOT NULL,
 is_spell    boolean NOT NULL,
 attack_name text NOT NULL,
 CONSTRAINT PK_attacks PRIMARY KEY ( characters.id )
);







